#  ____                       _    __                      _
# / ___| _ __ ___   __ _ _ __| |_ / _| __ _  ___ ___      (_) ___
# \___ \| '_ ` _ \ / _` | '__| __| |_ / _` |/ __/ _ \     | |/ _ \
#  ___) | | | | | | (_| | |  | |_|  _| (_| | (_|  __/  _  | | (_) |
# |____/|_| |_| |_|\__,_|_|   \__|_|  \__,_|\___\___| (_) |_|\___/
# -----------------------------------------------------------------

language: node_js
node_js:
  - "7.2.0"